### ISSUE TITLE
Index out of range 

### ISSUE THREAD

**Issue by Matteximond** [AnKing-VIP/ankiweb-placeholder#100]
the following comes up when i search for cards, how do i fix that 
![image](https://github.com/AnKing-VIP/ankiweb-placeholder/assets/167874807/7c619973-46e9-4d8e-8260-26d043696c58)

**Comment by AnKingMed** [comment]
What did you do prior to this? I have no idea what this is from

**Comment by Matteximond** [comment]
I manage to solve that but now i get this error and i have version 10 downloaded from the website this morning. is there anything i can do. 
![image](https://github.com/AnKing-VIP/ankiweb-placeholder/assets/167874807/2485b97e-93dd-4866-bd12-1911c4cb8d4b)

**Comment by Matteximond** [comment]
Prior to that i had reset my anki so it did not have a dec version selected

**Comment by Matteximond** [comment]
<img width="607" alt="image" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/167874807/4c9f5a08-ee95-4c76-8429-1784bc92156a">
i have the following dec

**Comment by AnKingMed** [comment]
What version of uworld are you using? Step or comlex? Step 1 or 2?

**Comment by Matteximond** [comment]
Comlex

**Comment by AnKingMed** [comment]
Comlex for step 1 is mostly done. Comlex for step 2 still has a lot of work to be done unfortunately

**Comment by AnKingMed** [comment]
@abdnh maybe we could update the addon to prompt a switch to auto if returning no results?

**Comment by Matteximond** [comment]
its still giving me the same error 
<img width="1440" alt="image" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/167874807/694e400b-26df-48f5-b551-a39d372a867e">

**Comment by abdnh** [comment]
> maybe we could update the addon to prompt a switch to auto if returning no results?

@AnKingMed Will have a look.

> its still giving me the same error

@Matteximond that's a different error, and is expected if there are no matching notes
