### ISSUE TITLE
New Cards Counter Issue

### ISSUE THREAD

**Issue by nihitkhandelwal-eng** [AnKing-VIP/ankiweb-placeholder#102]
## Which add-on is this about?
New Cards Counter

#### Problem description
There are 3 sections in the addon
- Total new cards learned today
- Total new cards learned this week
- New unsuspended cards

The first 2 sections, i.e. "new cards learned today & this week" are not working & they are not being updated
I have tried all the possible things, but I don't know what's happening, I even tried to reset the card including the lapses & repetition count, but it did not work.

I am attaching a screen recording to demonstrate the same
https://github.com/AnKing-VIP/ankiweb-placeholder/assets/68077636/6630a604-8408-4d2b-ba7d-02c4b4954615

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

```
Version ⁨23.12.1
```

**Comment by AnKingMed** [comment]
@AnKing-Forrest can you help troubleshoot?

**Comment by AnKing-Forrest** [comment]
This addon is working for me as intended. Have you downloaded the newest version? If so, and it's still not working, send me a screenshot of you configuration.

**Comment by nihitkhandelwal-eng** [comment]
Yes, I downloaded the latest version, here is the screenshot of my configuration
![Screenshot 2024-05-25 230924](https://github.com/AnKing-VIP/ankiweb-placeholder/assets/68077636/2e67f7fe-a517-4cc1-a3ee-cec15183f529)

**Comment by AnKing-Forrest** [comment]
Which Anki version are you currently using? I would try to suspend all of the other add-ons in your Anki program and then try again to see if it works. You have the same configuration as I do and mine is working well. This could be a result of interference from another addon.

**Comment by nihitkhandelwal-eng** [comment]
Will do that, however I had the addon disabled, enabled it again, & it works fine for the few new cards that I did, will see if it holds up when I do more new cards.
If not, I will disable other addons to rule out interference.
Thanks for your help!

**Comment by AnKing-Forrest** [comment]
That's great news!
