### ISSUE TITLE
Google Doc Decks remote add-on deck not syncing or tutorial needs to be improved

### ISSUE THREAD

**Issue by LK2408** [AnKing-VIP/ankiweb-placeholder#103]
## Which add-on is this about?
Google Docs add-on

#### Problem description
I followed the steps on the add-on page. I spent two hours on it and tried that it syncs. The formatting can't be wrong. I copied the documents from the add-on page. The deck gets created after inserting the link from the google doc. But I click on sync and nothing happens

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by krugspen** [comment]
I am having the same problem

**Comment by AnKingMed** [comment]
Any additional details you can share would be helpful.  Screenshot of your settings, link to the page you're using (the web link, not the doc link, etc)

**Comment by sherifsamy0006** [comment]
I have the same problem , after doing all the steps , the deck is created but with empty cards

**Comment by LK2408** [comment]
https://docs.google.com/document/d/e/2PACX-1vRnKVeGEIQrUTh6N-cge9odH-k6E4LKCZuWXfdCr824ml5wyWZz_rxKR-TgxDHM9XHEVPtJofXK7UZA/pub
https://docs.google.com/document/d/e/2PACX-1vTL2tssrVpVmAgGpTgs4SqKYXuoPNxYYLF2NdBXQvtyScz_On82-rsAv8eP9wWP1-1as5AWSYEsuSPS/pub
<img width="318" alt="Remote Deck url" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/150504844/7bcad0b0-e65f-4f98-adc6-0b5974b55f67">
<img width="805" alt="Remote decks" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/150504844/bbb61f67-f2e7-4d2c-9458-382dd4579dcd">
<img width="796" alt="add deck shortcut" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/150504844/1b585423-1e11-46ce-9bb3-053b70f40617">
<img width="251" alt="Adding cards to" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/150504844/779c43ec-2b6d-4cc3-9302-be0ad5fb3062">
<img width="247" alt="Adding cards to2" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/150504844/28b98631-68cb-46cf-8c51-adbb25f855b7">
<img width="233" alt="Sync completed" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/150504844/6ee2698c-55e3-41bf-bdd4-a2ec304bb2ba">
<img width="805" alt="Remote decks" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/150504844/b03c150a-e19e-4176-b676-db94bd4534b0">

**Comment by AnKingMed** [comment]
It looks like our instructions were pulled over from the original add-on and didn't get updated. @AnKing-Forrest will fix that. Sorry about that. Here are the correct instructions:

Instructions are roughly the same, but the process for creating cards in the document is different as shown below.

Click [here](https://docs.google.com/document/d/17oB8IrIMTSwM99NaOWQG-RDK56kt8Haq2b84smW8h00/edit?usp=sharing) to see an example document with instructions

**Comment by AnKingMed** [comment]
@AnKing-Forrest we need to change the kajabi listings to "draft" as well now that it's released

**Comment by krugspen** [comment]
Is there a way to have a table in the document that doesn't become an ANKI card? Like a table that is strictly for note-taking purposes?

**Comment by AnKing-Forrest** [comment]
Yes, just don't title the table as a note or a card. You'll have to break the styling pattern by titling it something else or just avoiding a table altogether.
