### ISSUE TITLE
Is there a way to change the sync so that the cards are basic - reversed, and not basic? Thank you!!!

### ISSUE THREAD

**Issue by Eroxx** [AnKing-VIP/ankiweb-placeholder#108]
I don't see anything in the config file that would allow me to (easily) change this, and in the documentation, I only see this:

#Note type: Cloze .... 

So I tried #Note type: basic (and reversed card), and also #Note type: Basic Reversed, but neither worked.

 I'm hopeful there's a way - thank you!

**Comment by AnKingMed** [comment]
I think it needs to be `#Note type: Basic (and reversed card)`

**Comment by Eroxx** [comment]
Thank you so much!!!

One more question: Is there any way I can change the parent deck to another name besides: "Remote decks"?

**Comment by AnKingMed** [comment]
At the moment no sorry!

**Comment by Eroxx** [comment]
Thanks for the quick response!

**Comment by Eroxx** [comment]
Last thing, I don't know if this is helpful to you, but I used AI to help write a script within google docs that will take text like this:

A
B
C
D

and convert it so that the remote anki add-on can read it (it's currently set to reversed cards):

-----

function formatTextWithSingleColumnTables() {
    var doc = DocumentApp.getActiveDocument();
    var body = doc.getBody();
    var text = body.getText().replace(/\n+/g, '\n'); // Normalize newlines

    var lines = text.split('\n').filter(line => line.trim() !== '');

    for (var i = 0; i < lines.length; i += 2) {
        if (lines[i] && i + 1 < lines.length && !lines[i].includes("# Note type: Basic (and reversed card):")) {
            var existingTables = body.getTables();
            var shouldCreateTable = true;

            for (var j = 0; j < existingTables.length; j++) {
                if (compareTableContent(existingTables[j], lines[i], lines[i + 1])) {
                    shouldCreateTable = false;
                    break;
                }
            }

            if (shouldCreateTable) {
                body.appendParagraph("# Note type: Basic (and reversed card):");

                var currentTable = body.appendTable();
                var row1 = currentTable.appendTableRow();
                var row2 = currentTable.appendTableRow();
                setTableCellWithFormatting(row1, lines[i]);
                setTableCellWithFormatting(row2, lines[i + 1]);

                body.appendParagraph(''); // Add a blank paragraph after the table
            }
        }
    }
}

function compareTableContent(table, line1, line2) {
    var tableLines = getTableLines(table);
    return tableLines.includes(line1) && tableLines.includes(line2);
}

function getTableLines(table) {
    var lines = [];
    var rows = table.getNumRows();
    for (var i = 0; i < rows; i++) {
        var cells = table.getRow(i).getNumCells();
        for (var j = 0; j < cells; j++) {
            lines.push(table.getRow(i).getCell(j).getText());
        }
    }
    return lines;
}

function setTableCellWithFormatting(row, text) {
    var parts = text.split('**');
    
    parts.forEach(part => {
        var cell = row.appendTableCell();
        if (part.trim()) {
            cell.setText(part);
        }
    });
}

function doGet(e) {
    formatTextWithSingleColumnTables();
    var output = 'Document formatted successfully!';
    return ContentService.createTextOutput(output);
}

**Comment by AnKingMed** [comment]
cool, thanks for sharing!
