### ISSUE TITLE
Google Docs Remote Deck Hierarchical Tags?

### ISSUE THREAD

**Issue by krugspen** [AnKing-VIP/ankiweb-placeholder#109]
## Which add-on is this about?
Google Docs Remote Deck

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```

#### Your question

*A clear and concise question about the add-on.*
Is it possible to create hierarchical tags with the "#Tag:" feature in Google Docs Remote deck? For example: 
"# Tag: Foo::bar"

**Comment by AnKingMed** [comment]
Yes that should work
