### ISSUE TITLE
uworld_qid_to_anki_search menu does not appear after restarting Anki

### ISSUE THREAD

**Issue by minnuett** [AnKing-VIP/ankiweb-placeholder#110]
## Which add-on is this about?
uworld_qid_to_anki_search

#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*
I bought the bronze membership and downloaded the uworld_qid_to_anki_search add-on, added it to my tools, and then restarted Anki, but the Uworld menu did not appear after restarting anki (I did this twice), so I am unable to use the add-on.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using? 

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
Version ⁨24.06.3 (d678e393)⁩
```

#### Error message (if any)

None

```

```

**Comment by minnuett** [comment]
<img width="1506" alt="Screen Shot 2024-07-20 at 6 34 17 PM" src="https://github.com/user-attachments/assets/5db73656-36b9-4e39-b631-cce100bf74cf">
<img width="615" alt="Screen Shot 2024-07-20 at 6 34 32 PM" src="https://github.com/user-attachments/assets/34d94a40-129c-4926-a0a5-cf000ed24195">

**Comment by AnKingMed** [comment]
You need to be in the browser view "click browse"

**Comment by minnuett** [comment]
sorry, what do you mean by this? I am already a full browser view on Anki, or do you mean this would be how the uworld tab would be added to my browser as well?

**Comment by minnuett** [comment]
> You need to be in the browser view "click browse"

sorry, what do you mean by this? I am already a full browser view on Anki, or do you mean this would be how the uworld tab would be added to my browser as well?

**Comment by AnKingMed** [comment]
The photo you showed is the main screen. Click "browse" at the top to go to the browser view

**Comment by AnKingMed** [comment]
You can also use "B" as a shortcut

**Comment by minnuett** [comment]
i see, ok thank you! sorry for the confusion!
