### ISSUE TITLE
Uworld not showing up on top bar 

### ISSUE THREAD

**Issue by BruceTheCaboose** [AnKing-VIP/ankiweb-placeholder#112]
## Which add-on is this about? 
Uworld QID look up 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```

#### Your question

*A clear and concise question about the add-on.*
My u world tab is not on the top bar. How do I fix it?

**Comment by AnKingMed** [comment]
You have to be in the browser view

**Comment by BruceTheCaboose** [comment]
I'm so sorry
