### ISSUE TITLE
UWorld2Anki Issue

### ISSUE THREAD

**Issue by jazmincandelario** [AnKing-VIP/ankiweb-placeholder#114]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using? Version ⁨24.06.3 (d678e393)⁩
*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##--> 24.06.3
```

#### Your question

*A clear and concise question about the add-on.* I am unable to see add on in UWorld. I am unable to see add on in Anki.

**Comment by jazmincandelario** [comment]
Is there any way to call you? I am struggling and could really use someone one the phone to help.

**Comment by AnKingMed** [comment]
You need to be in the browser view. Click "browse" at the top. 

We don't do phone calls sorry. We do offer video tutoring available through www.ankingmed.com/tutoring

**Comment by jazmincandelario** [comment]
Hi, I purchased my subscription today and would like to kindly ask if I can cancel it. Therefore, can I be refunded what was paid today?
