### ISSUE TITLE
UWorld to Anki problem finding add on code

### ISSUE THREAD

**Issue by jazmincandelario** [AnKing-VIP/ankiweb-placeholder#116]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
Version ⁨24.06.3 (d678e393)⁩
```

#### Your question I cannot find the code to input the add on.
![Screenshot 2024-08-09 at 6 36 44 PM](https://github.com/user-attachments/assets/75c897bd-2dd9-440c-9bfa-d40904295ade)

![Screenshot 2024-08-09 at 6 35 39 PM](https://github.com/user-attachments/assets/49f2b38d-45b5-4eab-a532-1717317e6c63)

*A clear and concise question about the add-on.*

**Comment by AnKingMed** [comment]
There is a download link near the bottom
