### ISSUE TITLE
PDF Exporter missing info

### ISSUE THREAD

**Issue by bguati** [AnKing-VIP/ankiweb-placeholder#123]
## Which add-on is this about?
PDF exporter

#### Problem description

*I've recently submitted an issue regarding this same thing. Now the save template is not causing the app to crash, but the "buttons" on the cards are still not clickable nor they are self expanding when exporting. I've uploaded a screenshot to illustrate the issue. If you could enlighten me on how to fix this, I'd appreciate. I wouldn't need the buttons to be actually clickable, if the content self expands/shows it will be more than enough. But the info inside each and everyone of those fields/buttons are super relevant to not be shown.

![image](https://github.com/user-attachments/assets/a499e246-4064-4d51-893b-ac400cb88e95)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
 ⁨24.06.3 (d678e393)⁩
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
I would recommend setting the template for the pdf so that you don't have buttons and just have the content of the fields. The pdf isn't meant to function like a webpage (or like the cards) so the interactive elements will not work because the javascript is not included
