### ISSUE TITLE
Weekend and Holidays help

### ISSUE THREAD

**Issue by nickmalbsn** [AnKing-VIP/ankiweb-placeholder#124]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
24.11
```

#### Your question

I want to set up the weekend and holidays add on to where all the review cards will be pushed back a day. But I'm talking about moving all the review cards (even the ones for later days) all by one day. Basically i want to shift all my review cards back a day. Is there any way to do this?

**Comment by AnKingMed** [comment]
This addon should do it: https://ankiweb.net/shared/info/1152543397
