### ISSUE TITLE
[Export Anki to PDF] Mathjax does not render in HTML + possible fix

### ISSUE THREAD

**Issue by camayl** [AnKing-VIP/ankiweb-placeholder#16]
#### Which add-on is this about?
Export Anki to PDF

#### Problem description
When exporting cards to HTML via the add-on, Mathjax is not rendered.

#### To Reproduce
To reproduce, use the add-on to export a deck that contains Mathjax as HTML. 

#### Checklist
 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
Version ⁨2.1.54 

#### Note
I found a fix in another add-on's (Basic Printing Support) comment section:

In Chrome: 
3-dot menu --> More Tools --> Developer Tools
Then paste the below into the Console and hit Enter:

```
function loadScript(src) {
var script = document.createElement("script");
script.src = src;
document.body.appendChild(script);
}
loadScript("https://polyfill.io/v3/polyfill.min.js?features=es6");
loadScript("https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js");
```

After hitting Enter, all Mathjax renders. When closing and reopening the HTML-file, this has to be done again for Mathjax to render.

I am unsure if this can be implemented into the add-on, so I am posting here.

**Comment by AnKingMed** [comment]
@RisingOrange any idea if this is possible with this add-on?

**Comment by RisingOrange** [comment]
@camayl Can you send me the exported .html file?

The add-on already does something very similar to the script you sent and mathjax rendering works for me. It's weird that it does not work for you.
What browser are you using?

If you want you can try to open this file and see if the `x^2` gets rendered by mathjax.
[Selected Notes.html.txt](https://github.com/AnKing-Memberships/ankiweb-placeholder/files/9734249/Selected.Notes.html.txt)
