### ISSUE TITLE
Can't get new cards counter to work

### ISSUE THREAD

**Issue by starbuck60** [AnKing-VIP/ankiweb-placeholder#17]
## Which add-on is this about?
New cards counter

#### Problem description
I upgraded to anking v12/infinity and ever since then the new cards counter does not work. I have done probably five hundred new cards since the upgrade and it only says I've done 8. I did around 200 new today and it says 0 new. The other new add on I'm running,  calculate new cards, is working fine--it is recalculating daily estimate based on the new cards I have done. 

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
How many of those cards was it the very first time you've done them?  If you go to the browser and type `introduced:7` how many cards show up?

**Comment by starbuck60** [comment]
There are only 5 cards that come up when I type indroduced:7. Not sure what this means but most of these new cards I'm doing are for the first time ever. I mostly made my own cards early on in preclinical and am now going through anking via unsuspending BnB videos after watching.

**Comment by starbuck60** [comment]
I recently did the ~200 cards for step 1 BnB purine/pyrimidine metabolism for the first time ever. It still shows as zero on the new card counter. Weird. Should I uninstall and try redownload new v12 deck? I have already uninstalled and reinstalled the addon. I had no problem with this addon with anking v11 for the 3-4 weeks I had been using 11 before the upgrade to 12/"infinity" deck.

**Comment by AnKingMed** [comment]
I'm not sure what to make of that. If you want to export your collection here I can try and take a look at it

Go to File->Export and select “.colpkg”. Then uncheck media, but include the scheduling.
