### ISSUE TITLE
Google Docs addon

### ISSUE THREAD

**Issue by hjordisasta** [AnKing-VIP/ankiweb-placeholder#35]
I haven't been able to get the google docs addon to work since autumn 2022. I waited for the update and downloaded it, but I still cannot get it to work. The name of my document shows up as a remote deck in Anki but no cards show up (the deck is empty).

**Comment by AnKingMed** [comment]
Can you send the link to your google doc with cards? You published it and linked it to the add-on, it just isn't downloading the cards?

**Comment by hjordisasta** [comment]
Thank you for the answer, yes I published and linked it. Anki creates the deck but doesn't create the cards. 
Here is the link: https://docs.google.com/document/d/e/2PACX-1vTajZsnPQXabwaFak1Z1WdeODhQHyRijpmbtRcLszgtHeSA_hz6Xz8YJMXAuX8Aumu2g-2qPDMmm338/pub

Thanks in advance!

**Comment by AnKing-Forrest** [comment]
Try copying and pasting the exact outline that we have provided in the example including the tables. Don't include bullet points. Also start your section of cards off with a heading (normal font, normal font size) with "# Note type: Cloze" and then create a two-row table with your cloze deletion and answer in there.
