### ISSUE TITLE
Add multiple tags to new card calculator 

### ISSUE THREAD

**Issue by burfang** [AnKing-VIP/ankiweb-placeholder#37]
## Which add-on is this about?
Calculate New Cards to do
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.54
```

#### Your question

*I have an exam coming up and would like to combine multiple tags into one query and one goal. How can I do that?*

**Comment by AnKing-Forrest** [comment]
First, search for all of the cards you want in the browse window by clicking on multiple tags while holding down "Shift." Then whatever search function worked for you to pull those cards up, copy that and paste it into your "Calculate New Cards to Do" search function and that query will be made into a new goal.
