### ISSUE TITLE
Uworld QID addon weird message V 19

### ISSUE THREAD

**Issue by Peter352598** [AnKing-VIP/ankiweb-placeholder#45]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the a
<img width="702" alt="Screenshot 2023-03-21 at 7 01 15 PM" src="https://user-images.githubusercontent.com/128552697/226760788-f0292203-3abe-4bec-8890-3af435c177d7.png">
dd-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
I don't think this is related to this addon. What were you trying to do
