### ISSUE TITLE
weekend and holiday rescheduler load balancer

### ISSUE THREAD

**Issue by epz2103** [AnKing-VIP/ankiweb-placeholder#46]
## Which add-on is this about?
weekend and holiday rescheduler

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.60
```

#### Problem case

*Is your feature request related to a problem? If so, please describe it here.  E.g.: "My workflow is such and such, and this and that would help."* 

there’s a huge difference in cards that are due before and after the day off and the rest of the week. For example, I take Saturdays off. So on a typical week, I could have 200 cards due Monday-Thursday, but then I would have 300 cards due on Sunday and Friday.

#### Solution

*Concisely describe the solution you would like*

I was hoping that maybe there was a way to level it out more so its more even throughout the week. Maybe something like spreading out those 200 cards that have to be rescheduled throughout the week so that each day has 233 cards due.
*Concisely describe alternatives you've considered (if any)*

#### More information

*Additional context: Add any other context or screenshots about the feature request here.*

**Comment by AnKingMed** [comment]
The addon moves cards further away when they are more mature. Are these relatively young cards? (i.e. smaller intervals).  The reasoning is that moving a card from 7 days to 12 days is less desirable than 60 days to 65 days
