### ISSUE TITLE
[Export Anki to PDF] Duplicate sentences in the answer section/removing tags from the final export

### ISSUE THREAD

**Issue by raveenak28** [AnKing-VIP/ankiweb-placeholder#55]
Export Anki to PDF  

I am using Anki Version ⁨2.1.62 Qt5. Currently the question in the answer section (back card) show up as duplicate sentences, like I've shown in the image. How do I go about removing that? 

![pdf exporter](https://github.com/AnKing-Memberships/ankiweb-placeholder/assets/72085254/51d82021-95e1-4b0b-9230-32fcc9d3942e)

Also I wanted to know if it's possible to remove the tags from the final export.

**Comment by AnKing-Forrest** [comment]
Are you on a Mac or a Windows? I haven't been able to reproduce the issue. Could you try re-downloading the Add-on? You can also send me your settings. Are you using the AnKing NoteTypes add-on? Before troubleshooting, we want to make sure you have the same AnKing Overhaul card type and styling.
