### ISSUE TITLE
UWorld QID

### ISSUE THREAD

**Issue by notorioussagittarius** [AnKing-VIP/ankiweb-placeholder#56]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using? V11

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.63 (f356f177)⁩
```

#### Your question

I downloaded the add-on yesterday and updated to the latest version of Anki and when I import QIDs, I get a message saying that the IDs do not exist:

<img width="1175" alt="Screenshot 2023-05-23 at 11 48 46 AM" src="https://github.com/AnKing-Memberships/ankiweb-placeholder/assets/134423386/b42e468f-6ac3-43fc-bb09-511a55cc2836">

I have the DO version of UWorld if that makes a difference. I also have V11 and Step 1 selected.

**Comment by AnKingMed** [comment]
24353,24697,25305 worked for me. Are you using a COMLEX version of UWorld? Are you using v12 of the deck or v11?

**Comment by notorioussagittarius** [comment]
Yes, I am using the COMLEX version and I am using v11 of the deck.

**Comment by AnKingMed** [comment]
As mentioned on our site, we primarily tagged based on the STEP version and UWorld wasn't willing to work with us and match them unfortunately so we have people tagging the COMLEX but it's very incomplete (as you notice I only had 3 of those tags). These tags are all being added to v12 only

**Comment by notorioussagittarius** [comment]
So do you recommend I download v12? Will I get more cards that way?

**Comment by AnKingMed** [comment]
You will get more uworld tags but as I mentioned it's still a work in progress and we don't have a ton yet. We're hoping to get more
