### ISSUE TITLE
[Calculate New Cards To Do]: Add on Freezes when returning to the deck screen.

### ISSUE THREAD

**Issue by Illuministica** [AnKing-VIP/ankiweb-placeholder#58]
#### Problem description

The add-on will freeze the entire Anki app if I return to the deck screen from any point, this includes whether I was finished with a review, searching for cards in the browser and so on. If I wait about a minute or two, it finally stops freeze and returns me back to the main deck screen. I do notice that the freeze time is considerably longer if Ankihub is present (from a minute to about 3 minutes) but with the recent ankihub update, it did not seem to replicate. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've tried to disable other add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

```
Version ⁨2.1.65, QT6
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
@RisingOrange I can't replicate this at all. Do you have any idea why this would interact with AnkiHub?

**Comment by Illuministica** [comment]
> @RisingOrange I can't replicate this at all. Do you have any idea why this would interact with AnkiHub?

I wanted to give an update because I wanted to test some combinations involving add-ons that involve the deck page in some way. I found a consistent way to reproduce the issue. I will also post some extra findings in hopes that I helps the team narrow it down.

1. The application crashes consistently when both Ankihub and Calculate New Cards is enabled, regardless of other add-ons enabled. Clicking "Deck" rapidly when I am reviewing a card causes Anki to consistently freeze and requires force quitting. This is not the case if I use the keyboard shortcut "D" to get back to the deck, but it is slower than normal to return to the deck, though at least it does freeze anymore. Neither Ankihub nor Calculate New Cards does this on their own. Furthermore, rapidly pressing "Deck" was by far the most reliable way to cause the issue, other methods were not as consistent (with pressing "D" producing the least amount of issues).

2. When the freeze occurs when Clicking "Deck" repeatedly from the card review screen, it seems to trigger a synchronization that never completes.

3. Ankihub on its own causes no issues, it plays nice with all the add-ons I have as long as its not calculate new cards, it returns to the deck screen at a snappy pace as expected no matter what I do. The Synchronization freeze event mentioned above also does not happen as long as calculate new cards is not enabled. 

4. Calculate New Cards increases the time to return to the deck screen significantly with any add-on, and especially with ones involving the screen (Amboss, Review Heatmap). I did not time how long it longed, but to give a guesstimate, it goes from instantaneous when the add-on is not available, to about 15 seconds when other add-ons are enabled. 

5. As long as the Calculate New Cards add-on is enabled, clicking "Deck" always took longer than pressing D. However, no freezes were seen with other add-ons, as long as Ankihub was disabled.

Hope this helps.

**Comment by AnKingMed** [comment]
Related conversation: https://community.ankihub.net/t/always-requires-force-quit/3925/18?u=nick

**Comment by RisingOrange** [comment]
I also couldn't reproduce this. @Illuministica, can you try disabling the `Show on main screen` checkbox for all goals in the settings for `Calculate new cards to do` and see if the problem goes away?

<img src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/31575114/d55f0983-fe6a-4c8e-a3ef-26b2cd8a11cc" width="500" />

**Comment by Illuministica** [comment]
> I also couldn't reproduce this. @Illuministica, can you try disabling the `Show on main screen` checkbox for all goals in the settings for `Calculate new cards to do` and see if the problem goes away?
> 
> <img alt="" width="500" src="https://user-images.githubusercontent.com/31575114/254007746-d55f0983-fe6a-4c8e-a3ef-26b2cd8a11cc.png">

The problem does in fact go away when I disable show menu on screen. Thank you so much! Any chance you would know why that would work?
