### ISSUE TITLE
Calculate New Cards To Do

### ISSUE THREAD

**Issue by loops214** [AnKing-VIP/ankiweb-placeholder#61]
## Which add-on is this about?
Calculate New Cards To Do
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?
2.1
*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```

#### Your question

The deck I want to study before a certain date has 2117 cards but the add on says that i only have to study 1109 news cards to study? 

*A clear and concise question about the add-on.*

**Comment by AnKingMed** [comment]
Can you screenshot the settings for your calculations?  

Can you look in the browser with that same search (the EXACT same one used in the addon settings) and tell me how many **cards** and how many **notes** there are for it? (use the toggle in the browser to see cards vs notes)

**Comment by loops214** [comment]
Here is the screenshot of calculations:
[A screenshot of a computer  Description automatically generated]

Here is the screenshot for notes and cards:
[A screenshot of a computer  Description automatically generated]
[A screenshot of a computer  Description automatically generated]

From: AnKingMed ***@***.***>
Date: Saturday, July 22, 2023 at 07:14
To: AnKing-VIP/ankiweb-placeholder ***@***.***>
Cc: loops214 ***@***.***>, Author ***@***.***>
Subject: Re: [AnKing-VIP/ankiweb-placeholder] Calculate New Cards To Do (Issue #61)

Can you screenshot the settings for your calculations?

Can you look in the browser with that same search (the EXACT same one used in the addon settings) and tell me how many cards and how many notes there are for it? (use the toggle in the browser to see cards vs notes)

**Comment by AnKingMed** [comment]
Nothing got uploaded. You'll have to view this thread on github and upload the images

**Comment by loops214** [comment]
Here is the screenshot of calculations:
<img width="534" alt="Screenshot 2023-07-22 at 10 26 37" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/140227519/07313567-8637-4ccf-bba1-3466a62aff0a">

Here is the screenshot for notes and cards:
<img width="874" alt="Screenshot 2023-07-22 at 10 28 15" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/140227519/a266507c-6be1-4594-96a5-7738677aba55">

![image](https://github.com/AnKing-VIP/ankiweb-placeholder/assets/140227519/d514411c-4f87-42bb-9081-1af9c43f53d2)

**Comment by AnKingMed** [comment]
Have you already studied some of the cards?

**Comment by loops214** [comment]
Oh okay now I see that it is showing me all the new cards instead of all of them. The calculated value does match all the new cards in the deck. So, is there a open to account for ALL cards instead just new ones?

**Comment by AnKingMed** [comment]
no because that's not really what the add-on is designed for.

**Comment by loops214** [comment]
good to know thank you for your prompt responses
