### ISSUE TITLE
Problem with Weekends and Holidays add on

### ISSUE THREAD

**Issue by saraFOgomes** [AnKing-VIP/ankiweb-placeholder#62]
## Which add-on is this about?
 weekends and holidays add on 

#### Problem description

I started to use weekends and holidays add on and I experimented put "wednesday, saturday anf sunday" without cards, just for trying. 
However, I don't want to have wednesday free and I can't change it now (and it put me free until november on wednesdays...). I already went to "edit-> undo rescheduling", restarted anki, sync again, went to advanced and configure it to "max days lookahead 7- to try to make it only happen 1 time-" but it doesn't work... I don't now what else can I do...
I only want to have saturday and sunday free, not wednesday. And even if wednesday is not selected now, in "move cards away from this days- I only have "saturday" and "sunday"-  . it doens't update this. 
Thank you very much!

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
version 2.1.65 (aa9a734f)⁩

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.65
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Once you reschedule things, if it's not giving you the opportunity to undo, you may not have that ability anymore. You can always restore a backup: 
How to Backup and Restore From Backup: https://www.youtube.com/watch?v=rHnUgNIJcR4&t=0s
