### ISSUE TITLE
IO one by one

### ISSUE THREAD

**Issue by clgubin** [AnKing-VIP/ankiweb-placeholder#63]
## Which add-on is this about?
IO one by one

#### Problem description

I am getting very frustrated because I have watched multiple videos and have tried to make my IO one by one cards for my images to study. When I right click at the end to occlude image literally nothing happens. I click accept occlusions and then underneath the IO section all it says is active... Can someone help me please!

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ X] I've restarted Anki to see if it helps
 - [X ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [X ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [X ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
The latest one
*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```
<img width="392" alt="Screen Shot 2023-08-05 at 12 12 05 PM" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/141515089/82773e9d-f5e7-455a-8a8c-10d615014164">

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```
<img width="321" alt="Screen Shot 2023-08-05 at 12 12 36 PM" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/141515089/392afa1d-11c0-4e85-b674-bea5a8ccc002">

**Comment by AnKingMed** [comment]
I'm sorry you're having this issue. What version of Anki are you on?

Can you go to a new profile, install the note type brand new using the AnKing Note Types add-on (make sure your addon is up to date) and then try it out again? If it's still not working, a screen recording would be helpful
