### ISSUE TITLE
AudioVisual Feedback conflicts with pokmanki

### ISSUE THREAD

**Issue by AmrAliDawoud** [AnKing-VIP/ankiweb-placeholder#64]
## Which add-on is this about?
AudioVisual Feedback

#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

I'm currently using Anki 2.1.65 Qt6. I use AudioVisual Feedback since it has been released as I am an Anking VIP member. The addon doesn't show images of themes (e.g. Bruce Lee, Silhouette, Kitten Rewards) during reviews when Pokmanki addon is enabled. This problem existed since Anki 2.1.49, but Pokmanki took time to be updated for next anki versions, so I just deleted it. Now, that Pokmanki is updated, the problem still exists. I downloaded the Audiovisual feedback from ankiweb hoping it was fixed, but it wasn't. When I disabled pokmanki alone, images of all themes appeared again and disappeared again with pokmanki enabled.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.65 Qt6
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
@abdnh can you look into this?

**Comment by abdnh** [comment]
I assume you're using this version of Pokemanki https://ankiweb.net/shared/info/1041307953? I found a critical bug in it that's breaking this add-on and probably a lot of other add-ons. I'll send a fix to the author.

**Comment by AmrAliDawoud** [comment]
Yes, this is the version I use, thanks.
