### ISSUE TITLE
Is New Cards Counter at all customizable?

### ISSUE THREAD

**Issue by sm0lp0t4t** [AnKing-VIP/ankiweb-placeholder#65]
## Which add-on is this about?

New Cards Counter

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.61
```

Am I supposed to be able to customize anything about this add-on, such as what day of the week it starts counting new cards, like it says in the add-on description?  The add-on currently displays the correct total from the past 7 days, but that's not what I was hoping to gain from it.  On my application there is no option to change settings anywhere.  Didn't want to make a bug report in case this was just a no longer supported feature.

*A clear and concise question about the add-on.*

**Comment by AnKingMed** [comment]
If you go to tools->addons and find the addon, click it, then click config you'll see all the options there. Does that answer your question?

**Comment by sm0lp0t4t** [comment]
Yes, sorry for the silly question!
