### ISSUE TITLE
Anki Sluggish

### ISSUE THREAD

**Issue by kw306** [AnKing-VIP/ankiweb-placeholder#66]
## Which add-on is this about?

None specifically 
#### Problem description

Anki is taking a long time to load and a few seconds to flip over cards and such. 

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

ankihub_addon_debug_info_19f27_1692658985.zip
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
Version ⁨2.1.65 (aa9a734f)⁩
*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.65
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
If this is for Anki please share on forums.ankiweb.net

If this is for AnkiHub, please share on community.AnkiHub.net
