### ISSUE TITLE
UWorld MCAT QIDs 

### ISSUE THREAD

**Issue by tforbes1** [AnKing-VIP/ankiweb-placeholder#69]
UWorld QID search addon for MCAT tags

Problem description

*This problem is specific to MCAT.* After QIDs are merged and synced, they do not show their correlated card after searching the QID in the addon. However, using the full tag in the anki search bar(e.g. #AK_MCAT_v2::#UWorld::402402) does pull up the correlated cards. To confirm, even after switching the addon settings from 'Auto' to 'MCAT' (or vice versa), putting in various QIDs into the addon still doesn't work. I've uninstalled, reinstalled, and had another user attempt, with all the same issues replicated. The QIDs and tags in the screenshot are all merged and synced and should be searchable on the addon. The addon continues to work for Step1,2,3, QIDs but just not for MCAT. 

<img width="497" alt="image" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/145166278/d4dc89fe-5c3e-44fd-abeb-4d8d68a86630">
<img width="459" alt="image" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/145166278/f3610bf3-d0f1-457d-b5d3-4383c462851c">
<img width="250" alt="image" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/145166278/e41b3d07-f402-464f-b75a-bf88e32a4e60">

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

What Anki version are you using? 

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.61
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
<img width="946" alt="image" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/145166278/8bdbc594-42ae-40a2-9dba-774f51b02ea5">

```

**Comment by AnKingMed** [comment]
@abdnh can you look into this? I think it's a bug
