### ISSUE TITLE
Weekends and Holidays Add-on not working with Anki Update

### ISSUE THREAD

**Issue by kpeezy24** [AnKing-VIP/ankiweb-placeholder#70]
#### Problem description

I recently updated to Anki 2.1.66 (QT6) and the weekends/holidays add-on is no longer working. I choose my setting for which days I want to skip, hit save, and when I go back to the configuration screen the settings I just input are completely gone and no cards have been rescheduled. I've tried disabling/re-enabling the add on, restarting Anki, etc and nothing seems to fix the problem.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ ] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.66
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
@AnKing-Forrest can you look into this?

@kpeezy24 are you using the latest version of the add-on? we did have a bug similar to this a bit ago and fixed it in the latest update

**Comment by AnKingMed** [comment]
@DoctorToBeIn23 just FYI. I don't think we'll test and try to support 2.1.66 because 2.23.10 is going to introduce pretty significant changes. My guess is our next supported version will be 2.23.11 or 2.23.12

@kpeezy24 for now we're recommending 2.1.64

**Comment by kpeezy24** [comment]
@AnKingMed I believe it's updated. I went to Tools > Add-ons > Check for updates and it says no updates available. 

I see. How do I downgrade to 2.1.64?

**Comment by AnKingMed** [comment]
It won't update that way. You have to download the version off the VIP site. 

How to Upgrade and Downgrade Anki Version (or use multiple!): https://www.youtube.com/watch?v=4Bqs_SzUWGE&t=4s

**Comment by kpeezy24** [comment]
@AnKingMed perfect. Thank you!
