### ISSUE TITLE
How to open an exclusive VIP add on if we are already members?

### ISSUE THREAD

**Issue by nikolas1s** [AnKing-VIP/ankiweb-placeholder#72]
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've checked if anyone else asked this question before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```

#### Your question

*A clear and concise question about the add-on.*

**Comment by AnKingMed** [comment]
You can download it from the VIP dashboard. There is a download link listed under each addon along with instructions. Just double click the .ankiaddon file and it should install in Anki. Then restart.
