### ISSUE TITLE
Pop up Dictionary Mobile- Turning off on computer platforms while maintaining functionality on mobile

### ISSUE THREAD

**Issue by kwhit513** [AnKing-VIP/ankiweb-placeholder#79]
## Which add-on is this about?
Pop up Dictionary Mobile

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [ x] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
23.12.1
```

#### Problem case

*Is your feature request related to a problem? If so, please describe it here.  E.g.: "My workflow is such and such, and this and that would help."* 

I currently have the glutanimate pop up dictionary and amboss running and this add on, while it is the best solution for mobile, lack some of the functionality of the pop up dictionary functionality (browser clicking, pop up within pop ups, multiword searches) and interferes on the computer platforms. 

#### Solution

*Concisely describe the solution you would like*
Making this add on have a "mobile only" configuration so it does not have functionality on computer versions of anki but is able to process on mobile versions.

*Concisely describe alternatives you've considered (if any)*

#### More information

*Additional context: Add any other context or screenshots about the feature request here.*

**Comment by AnKingMed** [comment]
@abdnh is this even possible?

**Comment by abdnh** [comment]
It's possible.

**Comment by AnKingMed** [comment]
Cool. We can keep this on our list for future ideas then!

**Comment by JChatara** [comment]
This is exactly what I came here to ask! Would LOVE to see this option implemented! 
For me this addon makes cards take 3-4x longer to load or flip to the back on my CP. but I don't notice hardly any lag if at all on the mobile app. (I tried limiting to only one note type, deck, or even just fields text and extra) no matter what I do it takes a long time (just to clarify, I know this is beta and am super grateful for it non the less!!) There are a couple cards where it takes more than 5 seconds to flip from the front to the back on my cp but instantly flips on the app.
I Agree with OP that it probably is stemming from all the other addons (like AMBOSS)

**Comment by AnKingMed** [comment]
@abdnh seems reasonable to me if you want to add it

**Comment by abdnh** [comment]
Added.

**Comment by AnKing-Forrest** [comment]
I've released the update on our AnKing VIP sites.
