### ISSUE TITLE
pop-up Dictionary addon doesn't show any results when a word contains letters "é" "è" "à" "ç" etc...

### ISSUE THREAD

**Issue by justarmadillo** [AnKing-VIP/ankiweb-placeholder#81]
## Which add-on is this about?

Mobile pop-up Dictionary

#### Problem description

I'm a french student, when a word contains the letters "é" or "è" "à" or other similar latters, The addon doesn't show any result, although if I search for the word manually in the browser I find results.
**I really really hope that you make a fast fix for CRITICAL issue, I can't use this addon anymore :(**

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
23.12.1
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
This is a known bug unfortunately. It doesn't work with other languages or symbols at the moment, but something we can keep on the list

**Comment by justarmadillo** [comment]
> This is a known bug unfortunately. It doesn't work with other languages or symbols at the moment, but something we can keep on the list

Is it on your quick fix list so I can wait, or it will take time ?
So I can make a workaround for it to work (replacing letters of my database with english letters to make it work)

**Comment by AnKingMed** [comment]
I don't know that we'll be pushing out a new version super quick. @abdnh I remember you saying symbols was possible but more difficult? Are these types of symbols easier to support if we still exclude stuff like chinese characters and such?

**Comment by abdnh** [comment]
This doesn't seem like a quick fix due to how search works in the add-on (using [lunr.py](https://github.com/yeraydiazdiaz/lunr.py)). The add-on basically splits the note contents into base words using language-specific rules (Only for English at the moment), so for example "say" and "said" might get converted to "say". This is to improve performance, storage and the search quality. If we simply make the add-on split words separated by spaces without doing any language-specific conversion (which might be what most users expect), the add-on will automatically work for all languages that use spaces, but we'll need to test how that performs. I'll do some tests soon.

**Comment by justarmadillo** [comment]
> This doesn't seem like a quick fix due to how search works in the add-on (using [lunr.py](https://github.com/yeraydiazdiaz/lunr.py)). The add-on basically splits the note contents into base words using language-specific rules (Only for English at the moment), so for example "say" and "said" might get converted to "say". This is to improve performance, storage and the search quality. If we simply make the add-on split words separated by spaces without doing any language-specific conversion (which might be what most users expect), the add-on will automatically work for all languages that use spaces, but we'll need to test how that performs. I'll do some tests soon.

Good luck brother

**Comment by abdnh** [comment]
> If we simply make the add-on split words separated by spaces without doing any language-specific conversion (which might be what most users expect), the add-on will automatically work for all languages that use spaces, but we'll need to test how that performs.

I turns out this is easy to implement. It'll increase the index file's size and will probably affect performance but I think it's worth trying (we can always revert the change or maybe add language-specific settings if this proves to be problematic). @AnKingMed What do you think?

**Comment by AnKingMed** [comment]
If it's going to decrease performance I'd probably only include it as a language specific setting

**Comment by abdnh** [comment]
Option added.
![image](https://github.com/AnKing-VIP/ankiweb-placeholder/assets/41397710/7dec7416-f304-4dd5-8304-4a2caeb38826)

I did a quick test with ~63K notes. The loading time went up half a second:
