### ISSUE TITLE
UWorld Add-on Menu not appearing after initial download (mac)

### ISSUE THREAD

**Issue by ih8notstudying** [AnKing-VIP/ankiweb-placeholder#92]
## Which add-on is this about?
UWorld QID to Anki Search

#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*
- I am a Bronze VIP Anking subscriber. 
- I downloaded the UWorld QID to Anki Search add-on from the Anking Mastery Courses website. 
- I opened the downloaded add-on. It said it successfully downloaded after I clicked through the menu saying it's a download from the internet and could have bad things on it. 
- I restarted anki and looked for a menu on the top that showed the Uworld options. It was not there. 
- I toggled off the add-on in the tools menu, quit anki, then restarted it. Then toggled it back on. Then restarted again. No menu. 
- I quit anki. Opened it again with the shift held down. No menu. I'm not sure what to do at this point. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the add-on by redownloading it from AnkiWeb
 - [x] I've tried to disable other add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
⁨23.12.1 (1a1d4d54)⁩
```

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
You have to be in the browser for the uworld menu to show up on the top bar (click "browse" at the top in the main screen)

**Comment by ih8notstudying** [comment]
Rookie mistake. My bad. I see the Uworld menu now! Thank you! 

I thought that the instructions about the browser meant that you have to have to be using it on a personal computer and not on an iPad or something. Thank you very much!
