### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by Matteximond** [AnKing-VIP/ankiweb-placeholder#99]
i can't seem to get it too work I have purchase the full version for step 2 and dowlad the Anking overhall for step 1 and 2 and the link is not working. can anyone help me.

**Comment by AnKingMed** [comment]
What can you not get to work?

**Comment by Matteximond** [comment]
Whenever I click on search Anki for missed questions or all questions the link doesn’t pull up anything. I have attached the images bellow to demonstrate.

A kind word is like a spring day,

Matthew Eximond OMS-II | Class 2025
LMU - DCOM at Knoxville
Community Events Chair- Surgery Club
National Representative - SAAO
***@***.***| (321) 274-3310
________________________________

**Comment by AnKingMed** [comment]
I don't see any images. Can you upload them on GitHub please?

**Comment by AnKingMed** [comment]
@DoctorToBeIn23 can you help?

**Comment by Matteximond** [comment]
<img width="1440" alt="Screenshot 2024-04-23 at 8 31 37 AM" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/167874807/d3109598-d569-4ce2-9aa6-80fa27e75d88">
<img width="1440" alt="Screenshot 2024-04-23 at 8 31 48 AM" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/167874807/6098ecfc-cf67-472b-a6ed-e958bbab09c9">
<img width="1440" alt="Screenshot 2024-04-23 at 8 32 10 AM" src="https://github.com/AnKing-VIP/ankiweb-placeholder/assets/167874807/d07a4755-3d19-46dc-9895-1bca2cf356dc">
